-- Databricks notebook source
--- Target table (report)

CREATE TABLE if not exists `datacube_rw`.`t_DataCube_Report` (
  `snapshot_date` TIMESTAMP,
  `portfolio_sys_updated_on` TIMESTAMP,
  `sys_class_name` STRING,
  `entry_beat_number` STRING,
  `count_ci_number` INT,
  `u_decomissioning_confirmed` STRING,
  `count_linked_bus_capabilities` STRING,
  `portfolio_entity_name` STRING,
  `u_business_capability_level_1` STRING,
  `u_business_capability_level_2` STRING,
  `u_business_capability_level_3` STRING,
  `u_user_counts` STRING,
  `development` STRING,
  `u_primary_client_type` STRING,
  `hosting` STRING,
  `u_hosting_location` STRING,
  `u_lead_business_portfolio` STRING,
  `u_lead_it_portfolio` STRING,
  `business_owner` STRING,
  `u_system_owner` STRING,
  `system_owner_delegate` STRING,
  `internal_lifecycle` STRING,
  `sys_created_on` TIMESTAMP,
  `sys_created_by` STRING,
  `sys_tags` STRING,
  `linked_organization_units` STRING,
  `count_legal_entities` STRING,
  `count_organizational_units` STRING,
  `count_linked_total_relationships` STRING,
  `count_linked_bus_applications` STRING,
  `count_linked_patterns` STRING,
  `count_linked_software_products` STRING,
  `count_users` STRING,
  `count_linked_application_services` STRING,
  `days_to_eol` STRING,
  `u_lead_business_portfolio_steward_name` STRING,
  `u_lead_business_portfolio_steward_email` STRING,
  `u_lead_business_portfolio_steward_u_it_status` STRING,
  `u_lead_business_portfolio_manager_department` STRING,
  `business_owner_email` STRING,
  `business_owner_u_it_status` STRING,
  `business_owner_department` STRING,
  `u_system_owner_email` STRING,
  `u_system_owner_u_it_status` STRING,
  `u_system_owner_department` STRING,
  `system_owner_delegate_email` STRING,
  `system_owner_delegate_status` STRING,
  `system_owner_delegate_department` STRING,
  `ci_number` STRING,
  `data_completeness` STRING,
  `data_currentness` STRING,
  `u_reputation_risk` STRING,
  `u_lead_it_portfolio_steward_name` STRING,
  `u_lead_it_portfolio_steward_email` STRING,
  `u_lead_it_portfolio_steward_u_it_status` STRING,
  `u_lead_it_portfolio_manager_department` STRING,
  `responsible_division` STRING,
  `number_of_business_capabilities` BIGINT,
  `score_apprat_capability_uniqueness` STRING,
  `score_apprat_hosting` INT,
  `business_criticality` STRING,
  `score_apprat_business_criticality` INT,
  `score_apprat_ea_assessment` INT,
  `avg_user_counts` BIGINT,
  `usage_percentile` STRING,
  `score_apprat_capability_usage` STRING,
  `u_linked_organization_units` STRING,
  `score_apprat_division_diversity` STRING,
  `u_serviced_by` STRING,
  `score_apprat_appliation_support` INT,
  `u_geographical_scope` STRING,
  `u_gxp_relevant` STRING,
  `score_apprat_geographical_scope` INT,
  `u_planning_start_date` DATE,
  `u_production_start_date` DATE,
  `u_expiring_start_date` DATE,
  `u_archived_start_date` DATE,
  `u_retired_start_date` DATE,
  `calc_eol` INT,
  `score_apprat_application_eol` STRING,
  `number_of_active_software` BIGINT,
  `number_of_expired_software` BIGINT,
  `number_of_sunset_software` BIGINT,
  `number_of_active_pattern` BIGINT,
  `number_of_expired_pattern` BIGINT,
  `number_of_sunset_pattern` BIGINT,
  `score_apprat_technology_retirement` STRING,
  `score_apprat_overall_usage` INT,
  `score_apprat_avg_technology_rationale` DOUBLE,
  `score_apprat_avg_business_rationale` DOUBLE,
  `apprat_quadrant` STRING,
  `technical_compliance` STRING,
  `standardization_status` STRING,
  `manufacturer` STRING,
  `type` STRING,
  `version` STRING,
  `license_type` STRING,
  `direct_technology_related` STRING,
  `direct_technology_type` STRING,
  `u_ics_classification` STRING,
  `u_controlled_data_classification` STRING,
  `u_data_privacy_classification` STRING,
  `u_foreign_trade_law_classification` STRING,
  `u_licensed_data_classification` STRING,
  `u_pre_patent_law_classification` STRING,
  `u_tax_classification` STRING,
  `u_kritis` STRING,
  `business_capability_number` STRING,
  `business_capability_name` STRING,
  `business_capability_sys_updated_on` TIMESTAMP,
  `u_business_capability_level` STRING,
  `u_business_capability_parent` STRING,
  `u_business_capability_parent_level` STRING,
  `u_business_capability_parent_parent` STRING,
  `u_business_capability_parent_parent_level` STRING,
  `u_business_capability_parent_parent_parent` STRING,
  `u_business_capability_parent_parent_parent_level` STRING,
  `u_business_capability_parent_parent_parent_parent` STRING,
  `u_business_capability_parent_parent_parent_parent_level` STRING,
  `relationship_parent_ci_number` STRING,
  `relationship_parent_class` STRING,
  `relationship_parent_ci_name` STRING,
  `relationship_parent_ci_beat_number` STRING,
  `relationship_child_ci_number` STRING,
  `relationship_child_class` STRING,
  `relationship_child_ci_name` STRING,
  `relationship_child_ci_beat_number` STRING,
  `relationship_child_decomissioning_confirmed` STRING,
  `relationship_child_internal_lifecycle` STRING,
  `relationship_child_standardization_status` STRING,
  `relationship_child_manufacturer` STRING,
  `relationship_child_steward` STRING,
  `relationship_child_lead_it_portfolio` STRING,
  `relationship_child_system_owner` STRING,
  `relationship_child_business_owner` STRING,
  `relationship_child_type` STRING,
  `relationship_sys_updated_on` TIMESTAMP)
USING delta



-- COMMAND ----------

-- Source View Portfolio element 

create
view if not exists datacube_rw.beat_x_inpgh_upmx_portfolio_element as
select
  p.`sys_updated_on_display_value` as `sys_updated_on_display_value`,
  pe.`sys_class_name_display_value` as `sys_class_name`,
  pe.`number` as `number`,
  pe.`u_decomissioning_confirmed` as `u_decomissioning_confirmed`,
  pe.`rel_bus_cap` as `rel_bus_cap`,
  pe.`name` as `name`,
  pe.`u_business_capability_level_1_display_value` as `u_business_capability_level_1`,
  pe.`u_business_capability_level_2_display_value` as `u_business_capability_level_2`,
  pe.`u_business_capability_level_3_display_value` as `u_business_capability_level_3`,
  pe.`short_description` as `short_description`,
  pe.`business_criticality_display_value` as `business_criticality`,
  pe.`u_geographical_scope_display_value` as `u_geographical_scope`,
  pe.`u_user_counts_display_value` as `u_user_counts`,
  pe.`development_display_value` as `development`,
  pe.`u_primary_client_type_display_value` as `u_primary_client_type`,
  p.`ref_x_inpgh_upmx_business_application_hosting_display_value` as `ref_x_inpgh_upmx_business_application_hosting`,
  pe.`u_hosting_location_display_value` as `u_hosting_location`,
  pe.`u_lead_business_portfolio_display_value` as `u_lead_business_portfolio`,
  pe.`u_lead_it_portfolio_display_value` as `u_lead_it_portfolio`,
  pe.`internal_lifecycle` as `internal_lifecycle`,
  pe.`u_planning_start_date_display_value` as `u_planning_start_date`,
  pe.`u_production_start_date_display_value` as `u_production_start_date`,
  pe.`u_expiring_start_date_display_value` as `u_expiring_start_date`,
  pe.`u_archived_start_date_display_value` as `u_archived_start_date`,
  pe.`u_retired_start_date_display_value` as `u_retired_start_date`,
  pe.`sys_created_on_display_value` as `sys_created_on`,
  pe.`sys_created_by` as `sys_created_by`,
  pe.`sys_tags_display_value` as `sys_tags`,
  p.`ref_x_inpgh_upmx_business_application_u_linked_organization_units` as `ref_x_inpgh_upmx_business_application_u_linked_organization_units`,
  pe.`u_legal_entities` as `u_legal_entities`,
  pe.`u_organizational_units` as `u_organizational_units`,
  pe.`n_outdated_software` as `n_outdated_software`,
  pe.`n_relationships` as `n_relationships`,
  pe.`rel_bus_app` as `rel_bus_app`,
  pe.`u_rel_pattern` as `u_rel_pattern`,
  pe.`rel_to_processes` as `rel_to_processes`,
  pe.`u_rel_software_product` as `u_rel_software_product`,
  pe.`n_users` as `n_users`,
  pe.`u_rel_application_service` as `u_rel_application_service`,
  p.`ref_x_inpgh_upmx_business_application_u_days_in_planning_bayer` as `ref_x_inpgh_upmx_business_application_u_days_in_planning_bayer`,
  p.`ref_x_inpgh_upmx_business_application_u_days_in_production_bayer` as `ref_x_inpgh_upmx_business_application_u_days_in_production_bayer`,
  p.`ref_x_inpgh_upmx_business_application_u_days_in_expiring_bayer` as `ref_x_inpgh_upmx_business_application_u_days_in_expiring_bayer`,
  p.`ref_x_inpgh_upmx_business_application_u_days_in_archived_bayer` as `ref_x_inpgh_upmx_business_application_u_days_in_archived_bayer`,
  pe.`days_to_eol` as `days_to_eol`,
  p.`u_lead_business_portfolio_steward_name` as `u_lead_business_portfolio_steward_name`,
  p.`u_lead_business_portfolio_steward_email` as `u_lead_business_portfolio_steward_email`,
  p.`u_lead_business_portfolio_steward_u_it_status_display_value` as `u_lead_business_portfolio_steward_u_it_status`,
  p.`u_lead_business_portfolio_manager_department_display_value` as `u_lead_business_portfolio_manager_department`,
  pe.`business_owner_display_value` as `business_owner`,
  p.`business_owner_email` as `business_owner_email`,
  p.`business_owner_u_it_status` as `business_owner_u_it_status`,
  p.`business_owner_department_display_value` as `business_owner_department`,
  pe.`u_system_owner_display_value` as `u_system_owner`,
  p.`u_system_owner_email` as `u_system_owner_email`,
  p.`u_system_owner_u_it_status` as `u_system_owner_u_it_status`,
  p.`u_system_owner_department_display_value` as `u_system_owner_department`,
  pe.`steward_display_value` as `steward`,
  p.`steward_email` as `steward_email`,
  p.`steward_u_it_status` as `steward_u_it_status`,
  p.`steward_department_display_value` as `steward_department`,
  pe.`comments` as `comments`,
  pe.`recommendation_display_value` as `recommendation`,
  pe.`u_serviced_by_display_value` as `u_serviced_by`,
  pe.`u_number` as `u_number`,
  pe.`u_gxp_relevant_display_value` as `u_gxp_relevant`,
  pe.`data_completeness` as `data_completeness`,
  pe.`data_currentness` as `data_currentness`,
  pe.`u_reputation_risk_display_value` as `u_reputation_risk`,
  p.`u_lead_it_portfolio_steward_name` as `u_lead_it_portfolio_steward_name`,
  p.`u_lead_it_portfolio_steward_email` as `u_lead_it_portfolio_steward_email`,
  p.`u_lead_it_portfolio_steward_u_it_status` as `u_lead_it_portfolio_steward_u_it_status`,
  p.`ref_x_inpgh_upmx_business_application_u_ics_classification_display_value` as `ref_x_inpgh_upmx_business_application_u_ics_classification`,
  p.`ref_x_inpgh_upmx_business_application_u_gxp_relevant_display_value` as `ref_x_inpgh_upmx_business_application_u_gxp_relevant`,
  p.`ref_x_inpgh_upmx_business_application_u_controlled_data_classification_display_value` as `ref_x_inpgh_upmx_business_application_u_controlled_data_classification`,
  p.`ref_x_inpgh_upmx_business_application_u_data_privacy_classification_display_value` as `ref_x_inpgh_upmx_business_application_u_data_privacy_classification`,
  p.`ref_x_inpgh_upmx_business_application_u_foreign_trade_law_classification_display_value` as `ref_x_inpgh_upmx_business_application_u_foreign_trade_law_classification`,
  p.`ref_x_inpgh_upmx_business_application_u_licensed_data_classification_display_value` as `ref_x_inpgh_upmx_business_application_u_licensed_data_classification`,
  p.`ref_x_inpgh_upmx_business_application_u_pre_patent_law_classification_display_value` as `ref_x_inpgh_upmx_business_application_u_pre_patent_law_classification`,
  p.`ref_x_inpgh_upmx_business_application_u_tax_classification_display_value` as `ref_x_inpgh_upmx_business_application_u_tax_classification`,
  p.`ref_x_inpgh_upmx_business_application_u_kritis_display_value` as `ref_x_inpgh_upmx_business_application_u_kritis`,
  p.`ref_x_inpgh_upmx_business_application_gdpr_relevant_display_value` as `ref_x_inpgh_upmx_business_application_gdpr_relevant`,
  p.`u_lead_it_portfolio_manager_department_display_value` as `u_lead_it_portfolio_manager_department`
from
  datacube_r.beat_x_inpgh_upmx_portfolio_element_view pe
  inner join datacube_r.beat_x_inpgh_upmx_portfolio_element_piped_values_view p on pe.`u_number` = p.`u_number`

-- COMMAND ----------

-- Source View CMDB
create
view if not exists datacube_rw.beat_cmdb_rel_ci as
select
  p.parent_u_number as `parent_u_number`,
  p.parent_sys_class_name_display_value as `parent_sys_class_name`,
  c.parent_display as `parent`,
  p.parent_ref_x_inpgh_upmx_portfolio_element_number as `parent_ref_x_inpgh_upmx_portfolio_element_number`,
  p.child_u_number as `child_u_number`,
  p.child_sys_class_name_display_value as `child_sys_class_name`,
  c.child_display as `child`,
  p.child_ref_x_inpgh_upmx_portfolio_element_number as `child_ref_x_inpgh_upmx_portfolio_element_number`,
  port.u_decomissioning_confirmed as child_u_decomissioning_confirmed,
  port.internal_lifecycle as child_internal_lifecycle,
  app.u_standardization_status_display_value as child_standardization_status,
  app.manufacturer_display_value as child_manufacturer,
  port.steward as child_steward,
  port.u_lead_it_portfolio as child_lead_it_portfolio,
  port.u_system_owner as child_system_owner,
  port.business_owner as child_business_owner,
  app.u_type as child_type,
  c.sys_updated_on
  
from
  datacube_r.beat_cmdb_rel_ci_view c
  inner join datacube_r.beat_cmdb_rel_ci_piped_values_view p on c.sys_id = p.sys_id
  left outer join datacube_rw.beat_x_inpgh_upmx_portfolio_element port
  on p.child_u_number = port.u_number
  left outer join datacube_r.beat_x_inpgh_upmx_business_application_view app
  on p.child_u_number = app.u_number
  
  where p.parent_sys_class_name_display_value = 'Business Application BEAT' 
and p.child_sys_class_name_display_value in ('Software Product BEAT', 'Pattern BEAT', 'Standard' , 'Mapped Application Service' ,'Web Server', 'Database Instance' )

-- COMMAND ----------

-- Source View Capabilities
create
view if not exists datacube_rw.beat_x_inpgh_upmx_report_pf2org_unit2cap2app as
select
  pf.`sys_updated_on` as `sys_updated_on`,
  p.`u_business_application_u_number` as `u_business_application_u_number`,
  pf.`u_business_application_display` as `u_business_application`,
  p.`u_business_capability_number` as `u_business_capability_number`,
  pf.`u_business_capability_display` as `u_business_capability`,
  pf.`u_differentiation` as `u_differentiation`,
  pf.`u_organizational_unit` as `u_organizational_unit`,
  pf.`u_portfolio` as `u_portfolio`,
  pf.`sys_updated_by` as `sys_updated_by`,
  pf.`sys_created_on` as `sys_created_on`,
  pf.`sys_created_by` as `sys_created_by`,
  pf.`sys_tags` as `sys_tags`,
  pf.`sys_mod_count` as `sys_mod_count`,
  p.`u_business_capability_level` as `u_business_capability_level`,
  p.`u_business_capability_parent_display_value` as `u_business_capability_parent`,
  p.`u_business_capability_parent_level` as `u_business_capability_parent_level`,
  p.`u_business_capability_parent_parent_display_value` as `u_business_capability_parent_parent`,
  p.`u_business_capability_parent_parent_level` as `u_business_capability_parent_parent_level`,
  p.`u_business_capability_parent_parent_parent_display_value` as `u_business_capability_parent_parent_parent`,
  p.`u_business_capability_parent_parent_parent_level` as `u_business_capability_parent_parent_parent_level`,
  p.`u_business_capability_parent_parent_parent_parent_display_value` as `u_business_capability_parent_parent_parent_parent`,
  p.`u_business_capability_parent_parent_parent_parent_level` as `u_business_capability_parent_parent_parent_parent_level`
from
  datacube_r.beat_x_inpgh_upmx_report_pf2org_unit2cap2app_view pf
  inner join datacube_r.beat_x_inpgh_upmx_report_pf2org_unit2cap2app_piped_values_view p on pf.sys_id = p.sys_id

-- COMMAND ----------

-- MAGIC %python
-- MAGIC dbutils.notebook.exit('SUCCESS')
